### ISSUE TITLE
Is it "powerful" instead of "power"

### ISSUE THREAD

**Issue by Celthi** [yanqi27/core_analyzer#66]
In the about section, it is said
<img width="709" alt="Screen Shot 2022-08-13 at 8 59 25 PM" src="https://user-images.githubusercontent.com/5187962/184495293-824d68e5-e087-4d24-ae7f-d3a9e93b4191.png">

> A power tool to...

is it should be 
> A **powerful** tool

@yanqi27

**Comment by yanqi27** [comment]
I think both words are ok. Each emphasizes on a slightly different aspect. As for `power`, the wikipedia says

`A power tool is a tool that is actuated by an additional power source and mechanism other than the solely manual labor used with hand tools. The most common types of power tools use electric motors. Internal combustion engines and compressed air are also commonly used.`

Therefore, I think it is ok to use `power tool` since core_analyzer is to free developer from the labor of manual work.

**Comment by Celthi** [comment]
> I think both words are ok. Each emphasizes on a slightly different aspect. As for `power`, the wikipedia says
> 
> `A power tool is a tool that is actuated by an additional power source and mechanism other than the solely manual labor used with hand tools. The most common types of power tools use electric motors. Internal combustion engines and compressed air are also commonly used.`
> 
> Therefore, I think it is ok to use `power tool` since core_analyzer is to free developer from the labor of manual work.

I see. I was thinking how to translate it into Chinese. "A power tool" is like "一个电源工具“，"A powerful tool' is ”一个强大的工具",

**Comment by yanqi27** [comment]
I think you can use a new word in Chinese. There is no need to translate word by word.

**Comment by Celthi** [comment]
Got it
